services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATA_SOURCE: db
      SESSION_SECRET: '1some_session-secret1'
      DATABASE_URL: postgresql://postgres:pass@localhost:5432/microblogdb
    ports:
      - 3333:3333
    volumes:
      - ./prisma:/usr/src/app/prisma:rw
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=microblog
      - POSTGRES_PASSWORD=pass
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
